### PR TITLE
Add commands by asset DTOs

### PR DESCRIPTION
**Pull request by boricj**
Needed for requesting list of assets supporting a particular power action.

### CODE REVIEW

**Review by eric3873 — APPROVED** [review]

**Review by perrettecl — CHANGES_REQUESTED** [review]
I think this should be inside asset source code and not here. @stark-dev  could you take a look ?

**Review by stark-dev — APPROVED** [review]

**Comment by stark-dev** [comment]
> I think this should be inside asset source code and not here. @stark-dev could you take a look ?

Not sure if this is intended to query directly `fty-nut` or existing assets. Currently I don't think we have a way to get the commands supported by an asset in `fty-asset`, is it something we should add?

**Comment by boricj** [comment]
Everything related to NUT commands is handled by the agent `fty-nut-command`. Similarly, IT actions on IT assets are handled by EMC4J2. `fty-asset` really has no concept of actions and no component in the system has a global overview of asset actions.

Folding all of this inside a centralized action provider mechanism is going to require lots of design and work, as actions provided by dedicated components (`fty-nut-command`, EMC4J2...) will need to be both registered for enumeration and delegated for execution, not counting the fact that this would be a cross-team endeavor. I'm not going to to that for now, so I'm just going to extend this particular provider of actions to address that particular use case instead.

**Comment by stark-dev** [comment]
> Everything related to NUT commands is handled by the agent `fty-nut-command`. Similarly, IT actions on IT assets are handled by EMC4J2. `fty-asset` really has no concept of actions and no component in the system has a global overview of asset actions.
> 
> Folding all of this inside a centralized action provider mechanism is going to require lots of design and work, as actions provided by dedicated components (`fty-nut-command`, EMC4J2...) will need to be both registered for enumeration and delegated for execution, not counting the fact that this would be a cross-team endeavor. I'm not going to to that for now, so I'm just going to extend this particular provider of actions to address that particular use case instead.

Thanks, with @perrettecl we were discussing the possibility of adding an advanced filter for listing assets based on some of their properties, but it is not necessarily related

**Comment by boricj** [comment]
Another technical solution has been selected.

**Pull request closed without merging**
